import datetime
x=datetime.datetime.now()
print(x)
print(x.year)
print(x.month)
print(x.day)
print(x.date)
print(x.strftime("%a"))
print(x.strftime("%A"))
print(x.strftime("%w"))
print(x.strftime("%j"))
print(x.strftime("%m"))
print(x.strftime("%B"))
print(x.strftime("%d"))
print(x.strftime("%D"))
